const ACTION_TYPES = {
    SIGN_OUT: null,
    SIGN_IN_WITH_GOOGLE: null,
    SET_AUTH_USER_STORE: null,
    SET_DATA_TO_LOCAL_STORAGE: null,
    REMOVE_DATA_FROM_LOCAL_STORAGE: null,
    REMOVE_ITEM_FROM_LOCAL_STORAGE: null,
    SET_AUTH_USER_DATABASE_ID_STORE: null,
    SET_USER_DATA_FROM_LOCAL_STORAGE_STORE: null,
    SET_CORRECT_ANSWER_DOC_ID_STORE: null,
    SET_QUIZ_DATA_FROM_LOCAL_STORAGE_STORE: null,
};
export default ACTION_TYPES;